### ISSUE TITLE
Persistent storage

### ISSUE THREAD

**Issue by lunemec** [lunemec/nanny#1]
Maybe there should be a persistent storage to save state of long running notifications (say days or more). There may be a need to restart Nanny or the underlying system might need to reboot.

I had a idea to have multiple nannys in distributed fashion, but later it came as a overkill.

Hmm. More thought required. Maybe sqlite will suffice. The simpler the better.

**Comment by jfonseca8** [comment]
Sorry, just to understand. Why would Nanny need to restart?

Just to clarify: you want someone to have access to an arbitrarily long log?

**Comment by jfonseca8** [comment]
Ah, I see. My fear with having Nanny constantly writing to an SQL database is the possibility of any data breaches. I suppose this wouldn't be an issue if one were to take the proper precautions.

**Comment by lunemec** [comment]
Well, I have almost finished sqlite implementation, so it would sit on the server anyway. It is implemented so there can be multiple databases supported, but I believe sqlite will suffice for now.

**Comment by jfonseca8** [comment]
Nice, I'd love to help out if anything else comes to mind.

**Comment by lunemec** [comment]
Fixed https://github.com/lunemec/nanny/commit/fef68fb0067e4d5f1144c11f8c7d5481e26d9ea2.
