### ISSUE TITLE
API protection

### ISSUE THREAD

**Issue by PhilipSchmid** [lunemec/nanny#20]
Hi @lunemec 

I thought it would make sense to continue the API protection discussion inside this issue instead of this PR https://github.com/lunemec/nanny/pull/19.

**Why would it make sense to add API protection using an API key?**

Real world use case:

Lately I found myself in the situation where we needed some kind of "Dead-Man-Switch" functionality to monitor a remote office's internet connectivity status. Because of the company's policy, it's not possible to set up a VPN, therefore the HTTP GET/POST must go over the internet. Nanny is deployed on a cloud provider and in front of Nanny there is a firewall and a reverse proxy. Nevertheless it would probably be nice to ensure only the specific application (e.g. curl cronjob) from the remote office can access the Nanny instance. The rest of the remote office should not be able to do so. That's currently not possible since all clients at the remote office are using a PAT to access the internet and therefore the firewall rule which restricts the source IP range is useless.

Any thoughts on this? Are there other reasons why or why not to add an API protection using API keys?

Thanks,
Philip

**Comment by lunemec** [comment]
Hi @PhilipSchmid ,
as I said in the PR #19 , I think the nanny should not handle this. Simple reverse proxy like Nginx can do these things.

With nginx you can secure the API with TLS, add basic-auth and limit the requests only to the IP of the cronjob.

You already have reverse proxy in the cloud, so is there any reason not to use it to secure nanny?

**Comment by PhilipSchmid** [comment]
@lunemec Thanks for your answer.

Well I guess for my specific use case it would be secure enough to use a RP with client certificate based authentication in front of Nanny.

Nevertheless, in general I think an API key would also simplify the deployment process for such deployments since then a user does not need to set up an additional RP service and configure the authentication on it. But does this argument justify the development effort to implement an API key? I guess - you are right - it's probably not. To still ease the way for such deployments, I think we could also provide an example `docker-compose.yml` file which already includes an RP service. This way users which needs a secured deployment of Nanny could just use this file instead of the already existing one which only contains the Nanny service itself. What do you think of this?

Thanks.

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid yes, we could provide the `docker-compose.yml` with reverse proxy config. But would we be able to provide it flexible enough? I mean, the reverse proxy is very tied to domain, TLS certs, and other configuration dependent on the use-case.

Also, most people who run nginx will not run it using docker-compose, but rather installed on a server somewhere, so it would not be useful for those (everywhere we run it, it is installed on some Debian machine in production). And for local development, there is no need for this.
