### ISSUE TITLE
HTTP notifier?

### ISSUE THREAD

**Issue by lunemec** [lunemec/nanny#24]
I was thinking of having pure HTTP notifier, that would POST the `notifier.Message` to some given URL in the notifier settings.

This might be useful for chaining nanny with some other software running on different machine.

**Comment by PhilipSchmid** [comment]
I would love to have this functionality since it could also be used for use cases like notifications via Telegram bot etc. Unfortunately I can't really program Golang :sweat_smile:  ..

**Comment by PhilipSchmid** [comment]
Closed by #38
