### ISSUE TITLE
Provide quay.io as alternate Container registry

### ISSUE THREAD

**Issue by PhilipSchmid** [lunemec/nanny#31]
Hi @lunemec 

Since Docker Hub introduced a rate limitation a few months ago, I think it would be nice to at least offer the people an alternate container registry hosting on [quay.io](https://quay.io/organizations/new/) (free "Open Source" plan). Do you agree? If so, would you like to create an organization there and invite me (username `philipschmid`), or should I simply create one by myself (and perhaps also invite you?)?

Thanks & regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid I created quay account `lunemec` so you can invite me. I tried to create the repository there, but the auth via github also requires me to authorise with my current company, and that is not something I want to do (I wanted to privately authorize, but I don't see the option).

So if you could please create the repository there and invite me, that would be great. Thanks.

**Comment by PhilipSchmid** [comment]
Hi @lunemec 
Awesome, thanks. I've just created the `nanny` org and invited you. The problem is, we have to move this Github "nanny" repo into an own "nanny" Github org, or you have to create the quay.io repo since I do not own this repository here (therefore I can't connect quay to it):

![image](https://user-images.githubusercontent.com/5549063/107851310-4e28f480-6e09-11eb-9a28-79dbb99a5dba.png)

What would you prefer?

Thanks & regards,
Philip

**Comment by PhilipSchmid** [comment]
@lunemec Any updates on this? :)

Also, could you please update the image on the Docker Hub? Thanks!

Regards,
Philip

**Comment by PhilipSchmid** [comment]
@lunemec Would it might be also possible for you to add me as admin to https://hub.docker.com/r/lunemec/nanny? This way I could set up the automated build, so new image versions are also automatically added there :).

Would be awesome if I could do this stuff this morning or next week as I have some time available for stuff like this at the moment.

Thanks & regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid you are there as collaborator, and I can't find option to make you admin!

**Comment by lunemec** [comment]
@PhilipSchmid sorry for all the delays, I have lots of real life stuff to take care of, I will try to get to this soon.

**Comment by PhilipSchmid** [comment]
Stale. Not interested anymore.
