### ISSUE TITLE
Allow names to be non-unique

### ISSUE THREAD

**Issue by skx** [lunemec/nanny#4]
As [mentioned on redit](https://www.reddit.com/r/golang/comments/8u1z03/introducing_nanny_nanny_is_a_monitoring_tool_that/e1fj4v8/) - you can allow names to be non-unique by keying off the combination of `source IP` + `name`.

This is extraordinarily useful, if you wanted to add the same alert to multiple hosts.  (For example on my systems I have a script called `/usr/local/bin/heartbeat` which fires off an event with "`name: heartbeat`" on a bunch of systems.    I don't need to use "`name: heartbeat-$(hostname)`")

Of course in my case I use something similar to nanny, [which is purppura](https://github.com/skx/purppura/).

**Comment by lunemec** [comment]
Fixed https://github.com/lunemec/nanny/commit/92f65ea32b0d465b9c36c7678007a701e43a9a75
