### ISSUE TITLE
Maintainability score dropped to C

### ISSUE THREAD

**Issue by PhilipSchmid** [lunemec/nanny#40]
Hi @lunemec and @thomae 

With the recent changes, the maintainability score from Code Climate dropped from an `A` to a `C`: https://codeclimate.com/github/lunemec/nanny/issues

Do you guys think it's possible and worth to refactor the code to eliminate the Code Climate findings?

Thanks & regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid good catch! Yeah, we should refactor some parts. But the report shows warnings for structs implementing a interface. Which is kinda incorrect.

It might help to have each Notifier in its own separate package, implementing the interface, that way it might be better in the report as a package implementing certain interface.

But yeah, definitely its worth to refactor.

**Comment by PhilipSchmid** [comment]
Stale. Not interested anymore.
