### ISSUE TITLE
Flexible alerting via external processes

### ISSUE THREAD

**Issue by skx** [lunemec/nanny#5]
You have the ability to raise alerts via printing to `STDERR`, but of course they won't reach humans.

I see you also have email, which is a good addition, but I suspect a lot of people who use these tools will want different "inform a human" mechanisms, for example:

* Posting to IRC
* Posting to Slack
* Sending a notification to a mobile, via pushover, etc.

The simplest way to do this is to inform humans by executing a user-specified command.  In my sysem I pipe the alert as JSON to an external binary - which then POSTs to pushover to raise an alert upon my mobile.

You might also consider "reminders".  I repeat the notifications until the event is cleared manually, or automatically.  Again this is flexible - pass the "notification_count" to the external process as part of your JSON-dump.  Some systems might auto-remind, others might not.  So you grant the notifier the ability to make that choice.  (i.e. If you don't want to repeatedly inform somebody via pagerduty you just ignore alerts where `notification_count > 1`.)

**Comment by lunemec** [comment]
The `stderr` is default notifier, in case you want to hook it up to syslog or other system. I implemented email and sentry notifications for now, and it is very easy to add more. Since I don't use Slack, IRC or pushover, if there would be users who used these, I might add them.

**Comment by lunemec** [comment]
The user-specified command is nice idea, maybe I'll add it later.

The reminders are nice idea, however I'm not sure how I feel about them. Primarily, I wanted to use this with sentry, where you can see a log of alerts you already fixed/looked at, and new ones.
I'm afraid that if notifier sends more reminders, users will consider it as spam (alert blindness).

I'll think about these more, thanks!

**Comment by skx** [comment]
Reminders are nice because they provide a hacky way to escalation.

For example I had a setup where:

* The first time an event became raised I received a notification on my phone.
* The tenth time an event continued to be raised my colleague would receive a notification on their phone
  * On the basis I was asleep, busy, or hadn't been able to fix the problem myself.
* All other reminders would be ignored.

That kind of behaviour is useful, but adding the logic to your core program is something you'd want to avoid - which is the main reason I went down the "external notification" route.  It mean sthat i don't need to write notifications for systems I don't use, but others might.

(I'm sure there are lots of situations where you might decide to notify differently - rather than globally.  For example if a hostname was "dev.example.com" you might just send an email, but if ti was "prod.example.com" you'd send an SMS.)

Anyway these are the kind of things that are fun to think about!

**Comment by skx** [comment]
(Guess this is "wishlist: notification via external process", but it has some unrelated thoughts on it.  Feel free to close :) )

**Comment by lunemec** [comment]
I'll leave it here for now. Using external process is a good idea, and I may implement it in the future.
