### ISSUE TITLE
Be more flexible in scheduling

### ISSUE THREAD

**Issue by skx** [lunemec/nanny#6]
Right now your "time to raise" is specified in seconds.

Some jobs might run once per day, but raising an alert in 90000 seconds (25 hours) is hard to express.  Perhaps you could allow units:

* 5s
* 10m
* 25h

Of course you could default to seconds if no unit is specified, to preserve backwards compatability!

**Comment by lunemec** [comment]
Fixed https://github.com/lunemec/nanny/commit/81e260b81ba256190020e551f57c834ee1d54a25
