### ISSUE TITLE
Provide a way to create nanny-pair when installed as .deb

### ISSUE THREAD

**Issue by lunemec** [lunemec/nanny#9]
Since .deb package provides systemd unit, there is no easy way for user to create 2 Nanny's monitoring each other (except editing systemd unit, which breaks upon update). Maybe this should be configurable in the .toml file.

**Comment by PhilipSchmid** [comment]
Perhaps this Systemd feature will help? -> https://opensource.com/article/20/12/multiple-service-instances-systemctl

**Comment by lunemec** [comment]
Thanks. It might. I've not needed to use `.deb` packages for a long time now, we have everything in k8s via helm charts, and I no longer install nanny by hand using debian packaging. This issue was mainly as a idea-keep, but I have no real world usecase for this.

Also, when I think about it, you would probably never want to have 2 Nanny instances on single machine anyway - SPOF problem. So most likely would be some kind of 3 node cluster setup or something similar.

**Comment by lunemec** [comment]
I'm closing this as I don't think it makes sense to have multiple instances on single node.

**Comment by PhilipSchmid** [comment]
Ah, you are already using Nanny inside a Helm chart? Would you be able & like to share your existing Helm chart then?

This would minimize the effort for https://github.com/lunemec/nanny/issues/30 or even make it completely unnecessary.

Thanks in advance!

Regards,
Philip

**Comment by lunemec** [comment]
@PhilipSchmid no, I'm not using Nanny anymore at all, sadly. But we are using k8s with helm charts mainly at work.

**Comment by PhilipSchmid** [comment]
Alright, got it. Thanks for clarification ;).
